INSERT INTO user_preference(QUANTUM_ID, SNOOZE_UNTIL, EMAIL, SMS, COMM_PREF)
VALUES ('API_TEST_USER', CURRENT_DATE + 1, 'me@test.com', '01234567890', 'EMAIL');
VALUES ('API_TEST_USER_OLD_P', CURRENT_DATE - 2, 'me@test.com', '01234567890', 'EMAIL');