version: '3.1'
services:

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: cmd-hmpps-auth
    ports:
      - '9090:8080'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9090/auth/health']
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  cmd-db:
    image: postgres:10.6
    networks:
      - hmpps
    container_name: cmd-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=root
      - POSTGRES_DB=public

networks:
  hmpps:
