spring:
  profiles:
    include: stdout

  flyway:
    locations: classpath:db/migration/h2,classpath:db/migration/general

  jpa:
    show-sql: true

  datasource:
    url: 'jdbc:h2:mem:cmd-api-db;MODE=PostgreSQL;'
    continue-on-error: true
    username: cmd
    password: dummy
    initialization-mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub

server:
  shutdown: immediate