spring:

  flyway:
    locations: classpath:db/migration/postgres,classpath:db/migration/general,classpath:db/migration/docker
    schemas: check-my-diary

  jpa:
    show-sql: true

  datasource:
    url: 'jdbc:postgresql://${DATABASE_ENDPOINT:localhost:5432}/${DATABASE_NAME:check-my-diary}'
    username: '${DATABASE_USERNAME:check-my-diary}'
    password: '${DATABASE_PASSWORD:check-my-diary}'

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://sign-in-dev.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json

oauth:
  endpoint:
    url: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
  client:
    id: my-diary
    secret: clientsecret

logging:
  level:
    uk.gov: DEBUG

application:
  notify:
    key: aaaaaaaaaa-11111111-1111-1111-1111-111111111111-11111111-1111-1111-aaaa-aaaaaaaaaaaa

csr:
  endpoint.url: http://localhost:8081

elite2api:
  endpoint.url: http://localhost:8082

server:
  shutdown: immediate
