spring:

  flyway:
    locations: classpath:db/migration/h2,classpath:db/migration/general

  jpa:
    show-sql: true

  datasource:
    url: 'jdbc:h2:mem:cmd-api-db;MODE=PostgreSQL;'
    username: cmd
    password: dummy

  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub
oauth:
  client:
    id: my-diary
    secret: clientsecret

logging:
  level:
    uk.gov: DEBUG

application:
  notify:
    key: aaaaaaaaaa-11111111-1111-1111-1111-111111111111-11111111-1111-1111-aaaa-aaaaaaaaaaaa

csr:
  endpoint.url: http://localhost:8081

elite2api:
  endpoint.url: http://localhost:8082

server:
  shutdown: immediate
