spring:

  datasource:
    url: 'jdbc:postgresql://${DATABASE_ENDPOINT:localhost:5432}/${DATABASE_NAME:cmd-api-db}'
    username: '${DATABASE_USERNAME:root}'
    password: '${DATABASE_PASSWORD:dev}'

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration/postgres,classpath:db/migration