spring:
  application:
    name: cmd-api
  profiles:
    include: stdout

  jpa:
    open-in-view: false
    show-sql: false

  datasource:
    hikari:
      maximum-pool-size: 15

server:
  port: 8080
  servlet:
    context-path: /
  forward-headers-strategy: native
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
  shutdown: graceful

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'info,health'
  health:
    probes:
      enabled: true
  endpoint:
    health:
      cache:
        time-to-live: 2000ms
      show-components: always
      show-details: always
    info:
      cache:
        time-to-live: 2000ms

application:
  to:
    defaultMonths: 3


#💩💩💩
csr:
  regions:
    - name: 1
      url: ${csr.region1.url}
    - name: 2
      url: ${csr.region2.url}
    - name: 3
      url: ${csr.region3.url}
    - name: 4
      url: ${csr.region4.url}
    - name: 5
      url: ${csr.region5.url}
    - name: 6
      url: ${csr.region6.url}

#💩💩💩
jwt:
  secret: ${jwt.secret.key:invalidValue}
