spring:
  application:
    name: cmd-api
  profiles:
    include: stdout

  codec:
    max-in-memory-size: 100MB

  jpa:
    open-in-view: false
    show-sql: false

  security:
    oauth2:
      client:
        registration:
          elite2-api:
            provider: hmpps-auth
            client-id: ${oauth.client.id}
            client-secret: ${oauth.client.secret}
            authorization-grant-type: client_credentials
            scope: read
        provider:
          hmpps-auth:
            token-uri: ${oauth.endpoint.url}/oauth/token

  datasource:
    hikari:
      maximum-pool-size: 25

  cache:
    cache-names: userDetails
    caffeine.spec: maximumSize=500,expireAfterAccess=600s,recordStats

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always

server:
  port: 8080
  servlet:
    context-path: /
  forward-headers-strategy: native
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
  shutdown: graceful

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'info,health'
  endpoint:
    health:
      cache:
        time-to-live: 2000ms
      show-components: always
      show-details: always
      probes:
        enabled: true
    info:
      cache:
        time-to-live: 2000ms

application:
  to:
    defaultMonths: 3

csr:
  regions:
    - name: 1
    - name: 2
    - name: 3
    - name: 4
    - name: 5
    - name: 6
