spring:

  flyway:
    locations: classpath:db/migration/h2,classpath:db/migration/general
    baselineOnMigrate: true

  jpa:
    show-sql: true

  datasource:
    url: 'jdbc:h2:mem:cmd-api-db;MODE=PostgreSQL;'
    username: cmd
    password: dummy

  h2:
    console:
      enabled: true
      path: /h2-console

oauth:
  client:
    id: my-diary
    secret: clientsecret

logging:
  level:
    uk.gov: DEBUG

application:
  notify:
    key: aaaaaaaaaa-11111111-1111-1111-1111-111111111111-11111111-1111-1111-aaaa-aaaaaaaaaaaa

api.base.url:
  hmpps-auth: http://localhost:9090
  prison-api: http://localhost:8082
  csr: http://localhost:8081

server:
  shutdown: immediate
