spring:

  flyway:
    locations: classpath:db/migration/postgres,classpath:db/migration/general,classpath:db/migration/docker

  datasource:
    url: 'jdbc:postgresql://${DATABASE_ENDPOINT:localhost:5432}/${DATABASE_NAME:public}'
    username: '${DATABASE_USERNAME:root}'
    password: '${DATABASE_PASSWORD:dev}'

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub