spring:

  flyway:
    locations: classpath:db/migration/h2,classpath:db/migration/general

  jpa:
    show-sql: true

  datasource:
    url: 'jdbc:h2:mem:cmd-api-db;MODE=PostgreSQL;'
    continue-on-error: true
    username: cmd
    password: dummy
    initialization-mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub

oauth:
  client:
    id: cmd-api-client
    secret: clientsecret

logging:
  level:
    uk.gov: DEBUG

application:
  notify:
    key: aaaaaaaaaa-11111111-1111-1111-1111-111111111111-11111111-1111-1111-aaaa-aaaaaaaaaaaa

server:
  shutdown: immediate