---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "refresh-shift-changes"
spec:
  schedule: "0 19 * * *"
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      activeDeadlineSeconds: 5400
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: "refresh-shift-changes"
            securityContext:
              runAsNonRoot: true
              runAsUser: 1000
            image: quay.io/ukhomeofficedigital/openjdk11
            command: ["/bin/sh", "-c"]
            args:
              - 'JWT=$(curl -X POST https://sign-in-dev.hmpps.service.justice.gov.uk/auth/oauth/token?grant_type=client_credentials -H "Content-Type: application/json" -H "Content-Length: 0" -H "Authorization: Basic $(echo -n {{ .Values.secrets.API_CLIENT_ID }}:{{ .Values.secrets.API_CLIENT_SECRET }} | base64)"); TOKEN=$(echo -n $JWT | grep -o -E "[-a-zA-Z0-9\._]{100,}"); STATUS=$(curl -w "%{http_code}" http://cmd-api.{{ .Values.cron.namespace }}.svc.cluster.local/notifications/send -H "Authorization: Bearer $(echo $TOKEN)"); echo $http_status; if [[ $http_status -eq 200 ]]; then exit 0; else exit 1; fi'
          restartPolicy: Never
          activeDeadlineSeconds: 5400
