apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ .Values.secrets.APPINSIGHTS_INSTRUMENTATIONKEY | b64enc | quote }}
  JWT_SECRET_KEY: {{ .Values.secrets.JWT_SECRET_KEY | b64enc | quote }}
  API_CLIENT_ID: {{ .Values.secrets.API_CLIENT_ID | b64enc | quote }}
  API_CLIENT_SECRET: {{ .Values.secrets.API_CLIENT_SECRET | b64enc | quote }}
