# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: quay.io/hmpps/cmd-api
  tag: latest
  port: 8080

env:
  JAVA_OPTS: "-Xmx1536m"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json"
  OAUTH_ROOT_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
  ELITE2API_ENDPOINT_URL: "https://api-dev.prison.service.justice.gov.uk"
  CSR_ENDPOINT_URL: "csr-api-dev.aks-dev-1.studio-hosting.service.justice.gov.uk"

cron:
  namespace: check-my-diary-dev