# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: quay.io/hmpps/cmd-api
  tag: latest
  port: 8080

env:
  JAVA_OPTS: "-Xmx1536m"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "https://sign-in.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json"
  OAUTH_ROOT_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
  CSR_REGION1_URL: "https://region1-api.check-my-diary-prod.hmpps.dsd.io/api"
  CSR_REGION2_URL: "https://region2-api.check-my-diary-prod.hmpps.dsd.io/api"
  CSR_REGION3_URL: "https://region3-api.check-my-diary-prod.hmpps.dsd.io/api"
  CSR_REGION4_URL: "https://region4-api.check-my-diary-prod.hmpps.dsd.io/api"
  CSR_REGION5_URL: "https://region5-api.check-my-diary-prod.hmpps.dsd.io/api"
  CSR_REGION6_URL: "https://region6-api.check-my-diary-prod.hmpps.dsd.io/api"

cron:
  namespace: check-my-diary-prod
