---
generic-service:
  autoscaling:
    minReplicas: 1
    maxReplicas: 2

  resources:
    requests:
      cpu: 150m
      memory: 1000Mi
    limits:
      cpu: 2000m
      memory: 2500Mi

  env:
    JAVA_OPTS: "-Xmx1536m"
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json"
    OAUTH_ENDPOINT_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    ELITE2API_ENDPOINT_URL: "https://api-preprod.prison.service.justice.gov.uk"
    CSR_ENDPOINT_URL: "https://csr-api-prprod.aks-live-1.studio-hosting.service.justice.gov.uk"
  
cron:
  namespace: check-my-diary-preprod
