---
generic-service:
  replicaCount: 4

  resources:
    requests:
      cpu: 150m
      memory: 1000Mi
    limits:
      cpu: 2000m
      memory: 2500Mi

  env:
    JAVA_OPTS: "-Xmx1536m"
    API_BASE_URL_HMPPS_AUTH: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    API_BASE_URL_PRISON_API: "https://api.prison.service.justice.gov.uk"
    API_BASE_URL_CSR: "https://csr-api.aks-live-1.studio-hosting.service.justice.gov.uk"

cron:
  namespace: check-my-diary-prod

generic-prometheus-alerts:
  rdsAlertsDatabases:
    cloud-platform-61e5a328954063a7: "check my diary"
