---
generic-service:
  replicaCount: 2

  resources:
    requests:
      cpu: 150m
      memory: 1000Mi
    limits:
      cpu: 2000m
      memory: 2500Mi

  env:
    JAVA_OPTS: "-Xmx1536m"
    API_BASE_URL_HMPPS_AUTH: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    API_BASE_URL_PRISON_API: "https://prison-api-preprod.prison.service.justice.gov.uk"
    API_BASE_URL_CSR: "https://csr-api-prprod.aks-live-1.studio-hosting.service.justice.gov.uk"

  scheduledDowntime:
    enabled: true
    startup: '20 6 * * 1-5' # Start at 6.20am UTC Monday-Friday
    shutdown: '50 21 * * 1-5' # Stop at 9.50pm UTC Monday-Friday
  
cron:
  namespace: check-my-diary-preprod

generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: syscon-nonprod
  rdsAlertsDatabases:
    cloud-platform-d07334102a08ef5d: "check my diary"
