ALTER TABLE "SHIFT_NOTIFICATION"
    ADD COLUMN ACKNOWLEDGED BOOLEAN DEFAULT FALSE NOT NULL;

UPDATE "SHIFT_NOTIFICATION"
SET "ACKNOWLEDGED" = TRUE
WHERE "READ" = TRUE
   OR "SENT_SMS" = TRUE
   OR "SENT_EMAIL" = TRUE;

ALTER TABLE "SHIFT_NOTIFICATION"
    DROP COLUMN "READ";

ALTER TABLE "SHIFT_NOTIFICATION"
    DROP COLUMN "SENT_SMS";

ALTER TABLE "SHIFT_NOTIFICATION"
    DROP COLUMN "SENT_EMAIL";

ALTER TABLE "SHIFT_NOTIFICATION"
    DROP COLUMN "DATE_TIME";

ALTER TABLE "SHIFT_NOTIFICATION"
    DROP COLUMN "LAST_MODIFIED_DATE_TIME_IN_SECONDS";

CREATE INDEX "SHIFT_NOTIFICATION_ACKNOWLEDGED" on "SHIFT_NOTIFICATION" (ACKNOWLEDGED);


ALTER TABLE "SHIFT_TASK_NOTIFICATION"
    ADD COLUMN ACKNOWLEDGED BOOLEAN DEFAULT FALSE NOT NULL;

UPDATE "SHIFT_TASK_NOTIFICATION"
SET "ACKNOWLEDGED" = TRUE
WHERE "READ" = TRUE
   OR "SENT_SMS" = TRUE
   OR "SENT_EMAIL" = TRUE;

ALTER TABLE "SHIFT_TASK_NOTIFICATION"
    DROP COLUMN "READ";

ALTER TABLE "SHIFT_TASK_NOTIFICATION"
    DROP COLUMN "SENT_SMS";

ALTER TABLE "SHIFT_TASK_NOTIFICATION"
    DROP COLUMN "SENT_EMAIL";

ALTER TABLE "SHIFT_TASK_NOTIFICATION"
    DROP COLUMN "DATE_TIME";

ALTER TABLE "SHIFT_TASK_NOTIFICATION"
    DROP COLUMN "LAST_MODIFIED_DATE_TIME_IN_SECONDS";

CREATE INDEX "SHIFT_TASK_NOTIFICATION_ACKNOWLEDGED" on "SHIFT_TASK_NOTIFICATION" (ACKNOWLEDGED);
