CREATE TABLE IF NOT EXISTS prison
(
    prison_id     VARCHAR PRIMARY KEY,
    csr_plan_unit VARCHAR NOT NULL,
    prison        VARCHAR NOT NULL,
    region        INT     NOT NULL
);

INSERT INTO prison (prison_id, region, csr_plan_unit, prison)
VALUES ('AGI', 2, 'Askham Grange', 'HMP Askham Grange'),
       ('AYI', 4, 'Aylesbury', 'HMP Aylesbury'),
       ('BFI', 5, 'Bedford', 'HMP Bedford'),
       ('BAI', 2, 'Belmarsh', 'HMP Belmarsh'),
       ('BWI', 4, 'Berwyn', 'HMP Berwyn'),
       ('BMI', 1, 'Birmingham', 'HMP Birmingham'),
       ('BSI', 1, 'Brinsford', 'HMP Brinsford'),
       ('BLI', 5, 'Bristol', 'HMP Bristol'),
       ('BXI', 3, 'Brixton', 'HMP Brixton'),
       ('BCI', 3, 'Buckley Hall', 'HMP Buckley Hall'),
       ('BNI', 4, 'Bullingdon', 'HMP Bullingdon'),
       ('BRI', 5, 'Bure', 'HMP Bure'),
       ('CFI', 4, 'Cardiff', 'HMP Cardiff'),
       ('CWI', 5, 'Channings Wood', 'HMP Channings Wood'),
       ('CDI', 5, 'Chelmsford', 'HMP Chelmsford'),
       ('CLI', 4, 'Coldingley', 'HMP Coldingley'),
       ('CKI', 6, 'Cookham Wood', 'HMP Cookham Wood'),
       ('DAI', 5, 'Dartmoor', 'HMP Dartmoor'),
       ('DTI', 1, 'Deerbolt', 'HMP Deerbolt'),
       ('DWI', 4, 'Downview', 'HMP Downview'),
       ('DHI', 1, 'Drake Hall', 'HMP Drake Hall'),
       ('DMI', 1, 'Durham', 'HMP Durham'),
       ('ESI', 6, 'East Sutton Park', 'HMP East Sutton Park'),
       ('EWI', 5, 'Eastwood Park', 'HMP Eastwood Park'),
       ('EYI', 6, 'Elmey - (Sheppey -EY)', 'HMP Elmley'),
       ('EEI', 5, 'Erlestoke', 'HMP Erlestoke'),
       ('EXI', 5, 'Exeter', 'HMP Exeter'),
       ('FSI', 1, 'Featherstone', 'HMP Featherstone'),
       ('FMI', 3, 'Feltham', 'HMP Feltham'),
       ('FDI', 6, 'Ford', 'HMP Ford'),
       ('FHI', 6, 'Foston Hall', 'HMP Foston Hall'),
       ('FKI', 2, 'Frankland', 'HMP Frankland'),
       ('FNI', 2, 'Full Sutton', 'HMP Full Sutton'),
       ('GHI', 3, 'Garth', 'HMP Garth'),
       ('GTI', 6, 'Gartree', 'HMP Gartree'),
       ('SPI', 4, 'Grendon & Spring Hill', 'HMP Grendon & Spring Hill'),
       ('GNI', 4, 'Grendon & Spring Hill', 'HMP Grendon & Spring Hill'),
       ('GMI', 5, 'Guys Marsh', 'HMP Guys Marsh'),
       ('HDI', 2, 'Hatfield', 'HMP Hatfield'),
       ('HVI', 3, 'Haverigg', 'HMP Haverigg'),
       ('HEI', 1, 'Hewell', 'HMP Hewell'),
       ('HOI', 4, 'Highdown', 'HMP Highdown'),
       ('HPI', 5, 'Highpoint', 'HMP Highpoint'),
       ('HII', 3, 'Hindley', 'HMP Hindley'),
       ('HBI', 5, 'Hollesley Bay', 'HMP Hollesley Bay'),
       ('HHI', 1, 'Holme House', 'HMP Holme House'),
       ('HLI', 2, 'Hull', 'HMP Hull'),
       ('HMI', 2, 'Humber', 'HMP Humber'),
       ('HCI', 4, 'Huntercombe', 'HMP Huntercombe'),
       ('ISI', 3, 'Isis', 'HMP Isis'),
       ('IWI', 4, 'Isle of Wight', 'HMP Isle of Wight'),
       ('KMI', 3, 'Kirkham', 'HMP Kirkham'),
       ('KVI', 1, 'Kirklevington', 'HMP Kirklevington'),
       ('LFI', 3, 'Lancaster Farms', 'HMP Lancaster Farms'),
       ('LEI', 2, 'Leeds', 'HMP Leeds'),
       ('LCI', 6, 'Leicester', 'HMP Leicester'),
       ('LWI', 6, 'Lewes', 'HMP Lewes'),
       ('LYI', 5, 'Leyhill', 'HMP Leyhill'),
       ('LII', 6, 'Lincoln', 'HMP Lincoln'),
       ('LHI', 2, 'Lindholme', 'HMP Lindholme'),
       ('LTI', 5, 'Littlehey', 'HMP Littlehey'),
       ('LPI', 3, 'Liverpool', 'HMP Liverpool'),
       ('LLI', 2, 'Long Lartin', 'HMP Long Lartin'),
       ('LNI', 1, 'Low Newton', 'HMP Low Newton'),
       ('MSI', 6, 'Maidstone', 'HMP Maidstone'),
       ('MRI', 2, 'Manchester', 'HMP Manchester'),
       ('MWI', 6, 'Medway', 'HMP Medway'),
       ('MDI', 2, 'Moorland', 'HMP Moorland'),
       ('MHI', 6, 'Morton Hall', 'HMP Morton Hall'),
       ('NHI', 2, 'New Hall', 'HMP New Hall'),
       ('NSI', 6, 'North Sea Camp', 'HMP North Sea Camp'),
       ('NWI', 5, 'Norwich', 'HMP Norwich'),
       ('NMI', 6, 'Nottingham', 'HMP Nottingham'),
       ('ONI', 6, 'Onley', 'HMP Onley'),
       ('PVI', 3, 'Pentonville', 'HMP Pentonville'),
       ('PDI', 5, 'Portland', 'HMP Portland'),
       ('PNI', 3, 'Preston', 'HMP Preston'),
       ('RNI', 6, 'Ranby', 'HMP Ranby'),
       ('RSI', 3, 'Risley', 'HMP Risley'),
       ('RCI', 6, 'Rochester', 'HMP Rochester'),
       ('SDI', 4, 'Send', 'HMP Send'),
       ('SFI', 1, 'Stafford', 'HMP Stafford'),
       ('EHI', 6, 'Standford Hill- (Sheppey -EH)', 'HMP Standford Hill'),
       ('SKI', 6, 'Stocken', 'HMP Stocken'),
       ('SHI', 1, 'Stoke Heath', 'HMP Stoke Heath'),
       ('STI', 3, 'Styal', 'HMP Styal'),
       ('SUI', 6, 'Sudbury', 'HMP Sudbury'),
       ('SLI', 6, 'Swaleside - (Sheppey -SL)', 'HMP Swaleside'),
       ('SWI', 4, 'Swansea', 'HMP Swansea'),
       ('SNI', 1, 'Swinfen Hall', 'HMP Swinfen Hall'),
       ('MTI', 5, 'The Mount', 'HMP The Mount'),
       ('VEI', 5, 'The Verne', 'HMP The Verne'),
       ('TCI', 3, 'Thorn Cross', 'HMP Thorn Cross'),
       ('UKI', 4, 'Usk & Prescoed', 'HMP Usk & Prescoed'),
       ('UPI', 4, 'Usk & Prescoed', 'HMP Usk & Prescoed'),
       ('WDI', 2, 'Wakefield', 'HMP Wakefield'),
       ('WWI', 3, 'Wandsworth', 'HMP Wandsworth'),
       ('WII', 5, 'Warren Hill', 'HMP Warren Hill'),
       ('WLI', 5, 'Wayland', 'HMP Wayland'),
       ('WEI', 2, 'Wealstun', 'HMP Wealstun'),
       ('WNI', 1, 'Werrington', 'HMP Werrington'),
       ('WYI', 2, 'Wetherby', 'HMP Wetherby'),
       ('WTI', 6, 'Whatton', 'HMP Whatton'),
       ('WRI', 2, 'Whitemoor', 'HMP Whitemoor'),
       ('WCI', 4, 'Winchester', 'HMP Winchester'),
       ('WHI', 2, 'Woodhill', 'HMP Woodhill'),
       ('WSI', 3, 'Wormwood Scrubs', 'HMP Wormwood Scrubs'),
       ('WMI', 3, 'Wymott', 'HMP Wymott'),
       ('MU_NBI', 4, 'L & D Newbold', 'L & D Newbold'),
       ('MU_DSTN', 1, 'DST', 'DST North'),
       ('MU_ADMIN', 1, 'HMP Admin', 'DST North'),
       ('MU_DSTS', 4, 'DST South', 'DST South'),
       ('MU_LTVS', 4, 'London & Thames Valley Search', 'London & Thames Valley Search'),
       ('MU_MAST', 1, 'Midlands Area Search Team', 'Midlands Area Search Team'),
       ('MU_NERS', 1, 'NE Regional Search Team', 'NE Regional search team'),
       ('MU_SWD', 5, 'SW Dogs Team', 'SW Dogs Team'),
       ('MU_WDST', 4, 'Wales DST', 'Wales DST'),
       ('MU_YAST', 2, 'YAST', 'YAST')









