DROP TABLE IF EXISTS "UserNotificationSetting" CASCADE;

DROP TABLE IF EXISTS "Notification" CASCADE;

DROP TABLE IF EXISTS "ShiftTaskNotification" CASCADE;

DROP TABLE IF EXISTS "Prison" CASCADE;

DROP TABLE IF EXISTS "NotificationConfiguration" CASCADE;